labels:
  - name: "breaking"
    color: "72152D"
    description: "A PR that is a breaking change"
  - name: "removed"
    color: "FB3F2E"
    description: "A PR that removes code"
  - name: "deprecated"
    color: "D6CC0D"
    description: "A PR that deprecates code"
  - name: "enhancement"
    color: "a2eeef"
    description: "New feature or request"
  - name: "bug"
    color: "d73a4a"
    description: "Something isn't working"
  - name: "dependencies"
    color: "0366d6"
    description: "Pull requests that update a dependency file"
  - name: "documentation"
    color: "0075ca"
    description: "Improvements or additions to documentation"
  - name: "chore"
    color: "58FBC8"
    description: "Janitor work"
  - name: "tests"
    color: "BEC9FA"
    description: "A PR that adds to testing"
  - name: "skip-release"
    color: "AC98B7"
    description: "A PR that is excluded from Release draft"
    from_name: "skip-changelog"
  - name: "invalid"
    color: "e4e669"
    description: "This doesn't seem right"
  - name: "reverted"
    color: "13AAB0"
    description: "A PR that was reverted and excluded from Release draft"
  - name: "major"
    color: "72152D"
    description: "Bumps major version number"
  - name: "minor"
    color: "F4B53A"
    description: "Bumps minor version number"
  - name: "patch"
    color: "32E17D"
    description: "Bumps patch version number"
  - name: "release"
    color: "215B05"
    description: "Pull requests should trigger release once merged"
  - name: "duplicate"
    color: "cfd3d7"
    description: "This issue or pull request already exists"
  - name: "github_actions"
    color: "000000"
    description: "Pull requests that update Github_actions code"
  - name: "good first issue"
    color: "7057ff"
    description: "Good for newcomers"
  - name: "help wanted"
    color: "008672"
    description: "Extra attention is needed"
  - name: "java"
    color: "ffa221"
    description: "Pull requests that update Java code"
  - name: "question"
    color: "d876e3"
    description: "Further information is requested"
  - name: "wontfix"
    color: "ffffff"
    description: "This will not be worked on"
  - name: ".NET"
    color: "7121c6"
    description: "Pull requests that update .net code"
  - name: "siba"
    color: "0e8a16"
    description: "Instruments"
  - name: "siba"
    color: "0e8a16"
    description: "Instruments"
