name: Docker build and push

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      image_title:
        required: true
        type: string
      image_description:
        required: true
        type: string
      image_context:
        default: '.'
        required: false
        type: string
      before_build:
        default: ''
        required: false
        type: string
    secrets:
      package_user:
        required: true
      package_password:
        required: true
      package_feed:
        required: false

jobs:
  build:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v3.0.1
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}
          labels: |
            org.opencontainers.image.title=${{ inputs.image_title }}
            org.opencontainers.image.description=${{ inputs.image_description }}
            org.opencontainers.image.vendor=Specshell
          tags: |
            type=schedule
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - name: Before Build
        if: inputs.before_build != ''
        run: |
          ${{ inputs.before_build }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name == 'release' && github.event.action == 'published' }}
          build-args: |
            "PACKAGE_FEED=${{ secrets.package_feed }}"
            "PACKAGE_USER=${{ secrets.package_user }}"
            "PACKAGE_PASSWORD=${{ secrets.package_password }}"
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          context: ${{ inputs.image_context }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run:
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
